POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "what up bitches check out my site yo",
    "author": "big dom",
    "url": "http://daphnes.netlify.app",
    "likes": 417315387
}